### ISSUE TITLE
Script throws an error on some models with Arachne

### ISSUE THREAD

**Issue by NoiZzz** [mfish38/GCode-Forge#1]
Hi!
On some files I get this error when using 3 walls and Arachne:
I attached 2 files I found to be problematic. Models with thicker walls are processed without issues.

EDIT: Changing infill direction also throws an error even with Classic Wall generator.
[adxl.zip](https://github.com/mfish38/GCode-Forge/files/14045016/adxl.zip)

`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\NoiZzz\AppData\Local\Programs\Python\Python312\Lib\site-packages\gcode_forge\__main__.py", line 69, in <module>
    main(sys.argv)
  File "C:\Users\NoiZzz\AppData\Local\Programs\Python\Python312\Lib\site-packages\gcode_forge\__main__.py", line 57, in main
    module.apply(gcode, options)
  File "C:\Users\NoiZzz\AppData\Local\Programs\Python\Python312\Lib\site-packages\gcode_forge\processors\accel_experiment.py", line 133, in apply
    accelerate_forward(line, junction_speed_mms, step_distance_mm, min_segment_length, acceleration_mmss)
  File "C:\Users\NoiZzz\AppData\Local\Programs\Python\Python312\Lib\site-packages\gcode_forge\processors\accel_experiment.py", line 75, in accelerate_forward
    current_start, slow_cut = split_distance_forward(current_start, step_distance_mm, min_segment_length_mm)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NoiZzz\AppData\Local\Programs\Python\Python312\Lib\site-packages\gcode_forge\edit_utils.py", line 173, in split_distance_forward
    traveled += current.annotation.distance_mm or 0
                ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'annotation'`

**Comment by mfish38** [comment]
Note that the acceleration module is an experiment for visualizing velocity (using a gcode viewer) as dictated by square corner velocity and acceleration. The generated output will likely not be printable as there are some junction velocities that will be 0. There is also a bug where it appears a bunch of successive junctions on a curve can overwrite each other in odd ways and display the wrong value. Right now the line_type_pa processor is pretty much the only usable module for prints.

I tried slicing the adxl mount with 3 walls and Arachne and it worked without issue. It looks like an error I may have fixed recently, so I would recommend updating to the latest and trying again. If that still doesn't work, could you provide a .3mf file and sliced gcode that does not work?

**Comment by NoiZzz** [comment]
It is latest version. I download it today :)
Ok, so here is example gcode and 3mf that fail to process:
[adxl.zip](https://github.com/mfish38/GCode-Forge/files/14045689/adxl.zip)

EDIT: Omg... I think I found it.Precise wall is causing this issue. It was so simple. I think I checked all settings but that one...

**Comment by mfish38** [comment]
I found the issue. It was due to when chopping up the line to show velocity values for accelerating out of a junction I failed to check if the end of file had been reached. I just pushed a fix.

**Comment by NoiZzz** [comment]
It works now! Thank you
